### ISSUE TITLE
super().__init__(*args, **kwargs) TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by mm-reza** [boxabhi/Youtube_Django_Channels#2]
Cant establish connection

**Comment by boxabhi** [comment]
Have you installed requirements.txt?

**Comment by mm-reza** [comment]
Hi there,
Thanks for your reply, I have fixed the issue, its working now. How can I show the live update in the All Orders section in the front page?
